[package]
name = "jeu1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "jeu1"
path = "src/lib.rs"

[dependencies]
rand = "0.8.5"
ui = { path = "../ui" }